# Generated by Django 5.2.4 on 2025-07-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=566)),
                ('resolution', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('download_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
